### ISSUE TITLE
「！」「？」の扱い

### ISSUE THREAD

**Issue by kenjis** [codeigniter-jp/user_guide_src_ja#11]
https://github.com/codeigniter-jp/user_guide_src_ja/pull/7 で提起されてますが、現在、翻訳での「！」「？」を全角にするか半角にするかで、揺れがあります。

ユーザガイド日本語版執筆基準
https://github.com/codeigniter-jp/user_guide_src_ja/blob/develop_japanese/TRANSLATION_STANDARDS.md
によれば半角となりますが、執筆基準じたいを変更することも考えられます。

どちらがいいでしょうか？

**Comment by noldor** [comment]
#74 にて「（」「）」を全角にする提案があり、合わせてこちらも全角にしたいと思います（「！」「？」が半角だとバランスが取れないため）
