### ISSUE TITLE
Google Docs の作業状況について

### ISSUE THREAD

**Issue by rochefort** [codeigniter-jp/user_guide_src_ja#52]
作業状況を翻訳完了にするワークフローについて
教えてください。
mergeされたら、翻訳した人間が自分で完了にするのでしょうか？

あと、現在の翻訳率もしくは、完了した割合みたいなのが見れたら
嬉しいかと思うのですが、どうでしょう？

**Comment by kenjis** [comment]
> mergeされたら、翻訳した人間が自分で完了にするのでしょうか？

はい、`作業状況`列に「翻訳完了」と記入をお願いします。

現在の翻訳率は
https://github.com/codeigniter-jp/ci_user_guide_translation
の `cmd.php` に計算ツールがあります。
原文と翻訳の行数が一致している前提である程度の翻訳率を計算できます。

**Comment by kenjis** [comment]
https://docs.google.com/spreadsheets/d/1ZWD5XqwH-Uo9X7MR644jbL6O8p5LxIngLT8M547H8wc/edit?pref=2&pli=1#gid=0
のC列の翻訳率を更新しました。

最初15%ほどだったので、25ポイントほど翻訳が進みました。

**Comment by rochefort** [comment]
更新ありがとうございます。

ちなみに翻訳完了なのに翻訳率が100%になっていないのは
何を意味しているのでしょうか？

**Comment by kenjis** [comment]
可能性としては、

1. 翻訳率の計算アルゴリズムの不備
2. 翻訳完了後に原文が更新されている

翻訳率は、翻訳する必要がなさそうな行を除いて、原文と異なる行の割合です。
https://github.com/codeigniter-jp/ci_user_guide_translation/blob/master/src/Calculator/TranslationRate.php 参照。

**Comment by noldor** [comment]
更新ありがとうございます。

generalディレクトリのうち私の作業したものは3月時点の原文ドキュメントから翻訳していますので、その部分は計算不備と思われます。
http://codeigniter-jp.github.io/user_guide_src_ja/general/creating_drivers.html
このページだとリストの部分を取り除けていないので翻訳率下がっています。これはもうしょうがないですね。

**Comment by rochefort** [comment]
なるほど。helperで異常に低いものがあるのは、.. のせいかもしれません。
「ファイル数での完了率」を見てみたかったので、行追加して表示するようにしてみました。
（問題あれば削除しますので、行ってください。）

現時点では、31.68% とまだ結構あるようです。

**Comment by noldor** [comment]
アップデート方法である installation/upgrade_120.rst ～ installation/upgrade_223.rst の31件を計算外にしてみました。39%になりました。さらにoverviewが翻訳済ですが記入がないので、40%は超えるといえると思います。

それでもまだ道半ば、ですね。。。

**Comment by rochefort** [comment]
readmeに追記した方がいいかもしれないですが、
一旦こちらのissueはcloseしておきます。
