### ISSUE TITLE
執筆基準での「(」「)」の扱い

### ISSUE THREAD

**Issue by kenjis** [codeigniter-jp/user_guide_src_ja#74]
#11 と近いですが、日本語の文章内のカッコは執筆基準によれば、現在は半角の`(`及び`)`になりますが、全角の`（`と`）`に変えたいです。

**Comment by noldor** [comment]
地の文では全角文字を使いたいので基本的に同意です。

「基本的に」と保留したのは2点あります。

◇Sphinx文法の記号と混ざらないようにするには
　・ASCII にある記号は半角を使う
を残したまま例外として全角を使う規定をしないといけないのがやや面倒です

◇[NEKOGETさん側の執筆基準](https://github.com/NEKOGET/ci_user_guide_src/wiki/日本語版執筆基準)で
　・丸括弧 ( ) の外側には、全角文字がきても半角文字がきても間に半角文字 1 文字分のスペースを入れる。
　　　・丸括弧 ( ) の内側には、全角文字がきても半角文字がきても間にスペースを入れない。
　　　・丸括弧 ( ) 内には句点は付けない。複数の文がある場合は、各文の間にだけ句点を付ける。
　　　・丸括弧が末尾にくる場合は、括弧の外に句点を付ける。
と明記があり、個人的にはさらなるややこしさを持ってしまいます（NEKOGETさん側を変更したいところですが）。

**Comment by kenjis** [comment]
補足ですが、全角に変えて前後の半角スペースは入れないように執筆基準を変えたいということです。

~~~
問い合わせ結果のフィールド数 (列数) を返します。
↓
問い合わせ結果のフィールド数（列数）を返します。
~~~

Sphinx文法記号やコードでは半角のままにしないといけないのは、仕方ないですね。

**Comment by noldor** [comment]
ああ、誤読を誘う書き方をしていました。すみません。

（）を全角にしたい、については同意なのですが、そうすると並行作業しているNEKOGETさん側の執筆基準と相反してしまうので、いままで同じものをコミットしていればよかったのですが、それができなくなるのが面倒なのです。
で、できればNEKOGETさん側も全角にしたいところなのですが……そちらはそちらでFuelPHPの翻訳基準とずれてしまうので、受け入れられないところと思います。

そうなると並行作業している私だけが半角全角使い分ければ平和なのですが、私個人としてはややこしさを抱えることになってしまうというのが困った点です。

**Comment by kenjis** [comment]
できれば、NEKOGETさんの翻訳も執筆基準を変えてもらうのがいいと思いますが。

それが無理なら、このケースでは全角から半角へなら文字列の単純な置き換えで対応できるように思いますので、全角で訳して、ＮＥＫＯＧＥＴさんの方へPRする直前にスクリプトで変換するとかでしょうか。

**Comment by noldor** [comment]
どちらにしても私の手間になっちゃうんで解決してないのですよ……。

しかし、あとから半角から全角に置き換えるのは辛いので、この件は早めに片づけたいと思います。1週間異論が出なければ、「（」「）」だけでなく「？」「！」も合わせて執筆基準を全角にしてしまいましょう。

**Comment by kenjis** [comment]
> 1週間異論が出なければ、「（」「）」だけでなく「？」「！」も合わせて執筆基準を全角にしてしまいましょう。

そうですね。

**Comment by noldor** [comment]
すいません、ミスりました。

**Comment by kenjis** [comment]
@noldor クローズでよいのではないですか？
まだ何か残ってますでしょうか？

**Comment by noldor** [comment]
実作業が残っていました。片づけました。
