### ISSUE TITLE
もとの「3.0.x から 3.1.x へのアップグレード」の翻訳を配置しなおす

### ISSUE THREAD

**Issue by noldor** [codeigniter-jp/user_guide_src_ja#86]
備忘的なissuesです。

翻訳元テキストに追従するにあたり、3.1.0で実現されたもの、されなかったものを選り分けるのは面倒だったため
もとの「3.0.x から 3.1.x へのアップグレード」の翻訳はごっそり消しました。

https://github.com/codeigniter-jp/user_guide_src_ja/commit/1441602c246eda2d99c242a353244e50e96213c1#diff-9acb04b5f71d083ba22c518c3daabce4

単に失うのも残念なので、適切な箇所に移したく思います。

**Comment by kenjis** [comment]
> 翻訳元テキストに追従するにあたり、3.1.0で実現されたもの、されなかったものを選り分けるは面倒だったため

どういうことでしょうか？なぜ選り分けるという作業が必要なのかがよくわからないです。

翻訳元テキストに追従するには、以下のコマンドを実行し、
https://github.com/codeigniter-jp/ci_user_guide_translation#how-to-update-develop-branch
`develop_japanese`に`develop`ブランチをマージするだけだったと思いますが？

**Comment by noldor** [comment]
作業前の翻訳文は https://github.com/codeigniter-jp/user_guide_src_ja/blob/f3e24dfffe4cdbafe8e4c1ee881e9a269232e7e7/source/installation/upgrade_310.rst
作業時の原文最新は https://github.com/bcit-ci/CodeIgniter/blob/develop/user_guide_src/source/installation/upgrade_310.rst

もはや別の文章になっていますので、マージするだけだと翻訳文は失われます。
別のファイルに移動したのだと思いますが、移動先で変更加わっていないかどうかの確認するのは大変なので別の日にさせてください。

**Comment by noldor** [comment]
https://github.com/codeigniter-jp/user_guide_src_ja/commit/ddc18fd2ce2687126d8bd79dbc9912193666eecb
作業終えました。
