### ISSUE TITLE
フォームバリデーション（検証） ルールリファレンスの中の間違い

### ISSUE THREAD

**Issue by 46-96** [codeigniter-jp/user_guide_src_ja#95]
greater_than
greater_than_equal_to

less_than
less_than_equal_to
上記の翻訳内容はそれぞれが逆になっていると思われます。

greater_than[0]でバリデーションを行うと「0より大きい値でなければ」ならず、エラーには０が含まれます。

**Comment by don2275** [comment]
@46-96    
ご指摘ありがとうございます。
